name: example
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 210441
          schedule-id: 20241026
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ https://hooks.slack.com/services/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 }}
          message: '<@U12345678> 달려달려~'
